### ISSUE TITLE
Inherited permissions not reliably shown in pages in sub-namespaces?

### ISSUE THREAD

**Issue by tomgreen** [cosmocode/aclinfo#1] opened 2011-03-11 01:27 UTC
I have a private Wiki using MySQL-based ACL. I have a number of groups, each of which have read-only access to group-specific namespaces, and each namespace has a tree of subnamespaces. ACLINFO in the Sidebar seems to only show a subset of the groups which have access to pages in subnamespaces.

My Namespace structure is similar to:
:internal
:external
    :external:servicedealer:ns1
    :external:servicedealer:ns2
        :external:servicedealer:ns2:ns2.1
    :external:distributor:ns1
    :external:distributor:ns2
        :external:group2:ns2:ns2.1
...and so on.

I have groups like:
@admin, delete everywhere of course
@contributor, upload everywhere
@staff, read everywhere
@subsidiary, ditto
@servicedealer, read in :external:servicedealer:*
@distributor, read in :external:distributor:*
...and so on.

My ACLINFO shows, typically, as below.
For :external:servicedealer:start
    @servicedealer has read permissions
    @staff has read permissions
    @administrator has delete permissions
    @contributor has upload permissions
    @subsidiary has read permissions
For :external:servicedealer:ns1:start
    @staff has read permissions
    @administrator has delete permissions
    @contributor has upload permissions
    @subsidiary has read permissions

If I set up, as a test, a heirarchical tree like :playground:dist:sd:oem:retail, with each group having read access to their named namespace:*, then ACLINFO for:
.:oem:start lists @oem and @distributor but not @servicedealer
.:retail:start lists @retailer and @servicedealer, but not @oem or @distributor

I am running Dokuwiki 20101107a installed (via Gentoo-Portage) with the ACL patch released a couple of months ago, whose bug I cannot currently find. ACLINFO is latest, updated via the Update control in the Admin Plugin Manager yesterday. I have ACLINFO running in a Sidebar as :
<code>
== Permissions info ==
~~NOCACHE~~
~~ACLINFO~~
</code>

I am using the Arctic template.
Plugin ACLauditor and the Admin ACL Manager show the expected ACL permissions.

Thanks.

**Comment by cgalo5758** [comment] 2019-04-16 03:37
I am having the same issue. I have ACLInfo on a sidebar along with "~~NOCACHE~~" and it gets the permissions for the namespace correctly, but it doesn't get them correctly for subnamespaces. This is a security concern for my org.

**Comment by ebora** [comment] 2020-08-26 09:57
I'm seeing this, too.

With a namespace structure `a:b:c:d` aclinfo displays correct information up until `a:b:c` but for `a:b:c:d` displays the permissions from the root namespace `a`.

This is based on observance only, I would be willing to do a bit of testing if I'd see some reaction here. But as the bug seems to be at least 9 years old, I suspect that any more effort on my side would be in vain...

**Comment by splitbrain** [comment] 2020-08-26 10:00
A pull request with unit tests wold be welcome.

**Comment by ebora** [comment] 2020-08-26 12:41
Unfortunately I'm no PHP developer. Or any other kind, really. But I'll look at it and see if that would be feasible for me to learn. You'll hear from me if I succeed. 

But maybe there are other takers? Or maybe not, if one considers how old the issue is ;-)

**Comment by ebora** [comment] 2020-10-06 13:26
Looks like the update from 01.10.2020 fixed the issue. 
At least my testcase is shown correctly, now.

**Comment by annda** [comment] 2020-10-06 17:22
fixed by #6

**Closed as completed by annda** 2020-10-06 17:22 UTC
